name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 darglint
        python_version=$(python -c 'import platform; _, minor, _ = \
          platform.python_version_tuple(); print("minor")')
        if [[ ${python_version} -ge 9 ]]; then
          python -m pip install -r requirements.txt
        else
          while read requirement; do
            if [[ $requirement == "qat==0.4.2" ]]; then
              echo "Unsupported module"
            else
              python -m pip install $requirement
            fi
          done < requirements.txt
        fi
    - name: Analysing the code with pylint
      run: |
        python_version=$(python -c 'import platform; _, minor, _ = \
          platform.python_version_tuple(); print("minor")')
        if [[ ${python_version} -ge 9 ]]; then
          pylint $(git ls-files 'src/*.py')
        else
          pylint src/pygats/formatters.py src/pygats/misc.py \
            src/pygats/pygats.py src/pygats/recog.py
        fi
    - name: Analysing the code with flake8
      run: |
        flake8 --ignore=E501,DAR101 ./src
